In [1]:
import bqplot
import numpy as np
import ipywidgets

In [2]:
x = np.arange(100) # integers 0->999
y = np.random.random(100) + 5 # random numbers with mean = 5

In [3]:
x, y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([5.60467288, 5.41686   , 5.99689063, 5.60659076, 5.49097911,
        5.65088596, 5.50134809, 5.38574072, 5.51072507, 5.96381314,
        5.65310011, 5.02132014, 5.18058657, 5.13170459, 5.42042256,
        5.2286572 , 5.26439158, 5.83217355, 5.47627698, 5.02192125,
        5.13790504, 5.53918113, 5.47623281, 5.83817646, 5.53663453,
        5.19010176, 5.86419686, 5.19656539, 5.12125111, 5.05653086,
        5.18571989, 5.12298431, 5.23620528, 5.69380747, 5.47513094,
        5.57886701, 5.86599085, 5.72776983, 5.90804853, 5.82447874,
      

In [4]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [5]:
lines = bqplot.Lines(x = x, y = y, scales = {'x': x_sc, 'y': y_sc})

In [6]:
ax_x = bqplot.Axis(scale = x_sc, label = 'X Value')
ax_y = bqplot.Axis(scale = y_sc, label = 'Y Value', orientation = 'vertical')

In [7]:
fig = bqplot.Figure(marks = [lines], axes = [ax_x, ax_y])
#display(fig) # you might also want to try "display"
# if you don't see the following fig, here is where
#  you might have to close and reopen your notebook
fig # note: just "fig" instead of "display(fig)" may also be an option for you

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

In [8]:
pz = bqplot.interacts.PanZoom( scales = {'x': [x_sc], 'y': [y_sc]})

In [9]:
fig = bqplot.Figure(marks = [lines], axes = [ax_x, ax_y], interaction = pz)
#display(fig)
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

In [10]:
x = np.random.random(100) # random points betweeon 0-1
y = np.random.random(100) # random points betweeon 0-1

In [11]:
# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
x_ax = bqplot.Axis(scale = x_sc, label = 'X')
y_ax = bqplot.Axis(scale = y_sc, label = 'Y', orientation = 'vertical')

In [12]:
# 4. marks
scatters = bqplot.Scatter(x = x,
                          y = y,
                          scales = {'x': x_sc, 'y': y_sc})

In [13]:
# 5. interactions
selector = bqplot.interacts.FastIntervalSelector(
            scale = x_sc, marks = [scatters]) 

In [14]:
# Finally: fig
fig = bqplot.Figure(marks = [scatters], axes = [x_ax, y_ax], interaction = selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale()), Axis(label='Y', orientation='vertical', scale=LinearScale()…

In [15]:
selector.selected

In [16]:
scatters.unselected_style={'opacity': 0.8} # when unselected, make the points a little see-through

scatters.selected_style={'fill': 'red', 'stroke': 'yellow'} # fill with red, outline in yellow when selected

In [17]:
fig = bqplot.Figure(marks = [scatters], axes = [x_ax, y_ax], interaction = selector)
#display(fig)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [18]:
# 1. Data
data = np.random.random((10, 10))
data # your's may look different!

array([[0.83386258, 0.66131092, 0.30616707, 0.12952678, 0.65566778,
        0.16116619, 0.02773062, 0.08890719, 0.5049114 , 0.96512567],
       [0.39072704, 0.74713902, 0.66999704, 0.26398933, 0.04049209,
        0.16325684, 0.61226735, 0.83670582, 0.25896888, 0.24050847],
       [0.86303308, 0.16546706, 0.41949558, 0.74928223, 0.42171839,
        0.45380948, 0.16917915, 0.90459024, 0.84742496, 0.82510525],
       [0.21877966, 0.23685799, 0.49947883, 0.48020547, 0.41151016,
        0.86339306, 0.5917742 , 0.6303728 , 0.63106561, 0.97159857],
       [0.44736744, 0.45175914, 0.9663266 , 0.88935923, 0.57595661,
        0.23445795, 0.59037257, 0.75632474, 0.22110723, 0.0647945 ],
       [0.78962015, 0.46251234, 0.49640791, 0.60052155, 0.62432943,
        0.5177485 , 0.50298289, 0.20811112, 0.97383948, 0.57795714],
       [0.10014749, 0.76274647, 0.80154178, 0.01055746, 0.93653792,
        0.13645751, 0.76370908, 0.64731329, 0.13248891, 0.42002828],
       [0.46664547, 0.34048827, 0.7774557

In [19]:
# 2. Scales -- in this case, just a color scale
col_sc = bqplot.ColorScale() # use bqplot to define a color scale

# 3. Axis -- skipping for now

# 4. Mark -- use colorscale to make make heatmap of our data:
heat_map = bqplot.GridHeatMap(color = data, scales = {'color': col_sc})

# 5. Skipping any interactions

# Finally: figure
fig = bqplot.Figure(marks = [heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.83386…

In [20]:
# 1. Data -- same as above

# 2. Scale -- color with new color scheme
col_sc = bqplot.ColorScale(scheme = "Reds") # color scheme of reds

# 3. skip Axis

# 4. Marks -- use colorscale to make make heatmap of our data:
heat_map = bqplot.GridHeatMap(color = data, scales = {'color': col_sc})

# Figure
fig = bqplot.Figure(marks = [heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.83386…

In [21]:
# 1. Data -- same

# 2. Scales -- color
col_sc = bqplot.ColorScale(scheme = "Reds")
# lets plot some axes on our plot as well, in this case
#  our axis will be a color bar, vertically on the right
#  of our heatmap

# 3. Axis (finally) -- here a "color axis" is just a colorbar
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right') 

# 4. Marks -- put it all together and lets take a look!
heat_map = bqplot.GridHeatMap(color = data, 
                              scales = {'color': col_sc})

# 5. no interactions

# generate fig!
fig = bqplot.Figure(marks = [heat_map], axes = [c_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right')], fig_margin={'t…

In [22]:
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

In [23]:
col_sc = bqplot.ColorScale(scheme = "Reds")

c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')

In [24]:
# Marks -- lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = data,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc})

In [25]:
fig = bqplot.Figure(marks = [heat_map], 
                    axes = [c_ax, y_ax, x_ax])

fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(orientatio…

In [26]:
# 1. Data -- same

# 2. Scales -- recopy our scales and axis for posterity:
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

# 4. Marks -- lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = data,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

# 5. Note: I put interactions in my marks call here!

# stir and combine into 1 figure
fig = bqplot.Figure(marks = [heat_map], 
                    axes = [c_ax, y_ax, x_ax])

fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(orientatio…

In [27]:
heat_map.selected
#  note if I select a different box & re-run this cell,
#  I get out different values

In [28]:
mySelectedLabel = ipywidgets.Label()

In [29]:
def on_selected(change):
    print(change)

In [30]:
# 1. Data -- same

# 2. Scales -- recopy our scales and axis for posterity:
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

# 4. Marks -- lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = data,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

# 5. Note: I put interactions in my marks call here.  BUT now we want to actually DO something with our selection
## THIS IS ALL WE HAVE ADDED!
heat_map.observe(on_selected, 'selected')


# stir and combine into 1 figure
fig = bqplot.Figure(marks = [heat_map], 
                    axes = [c_ax, y_ax, x_ax])

fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(orientatio…

In [31]:
def on_selected(change):
    print(change['owner'].selected)

In [32]:
# 1. Data -- same

# 2. Scales -- recopy our scales and axis for posterity:
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

# 4. Marks -- lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = data,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

# 5. Note: I put interactions in my marks call here.  BUT now we want to actually DO something with our selection
## THIS IS ALL WE HAVE ADDED!
heat_map.observe(on_selected, 'selected')


# stir and combine into 1 figure
fig = bqplot.Figure(marks = [heat_map], 
                    axes = [c_ax, y_ax, x_ax])

fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(orientatio…

In [33]:
# 1. Data -- same

# 2. Scales -- recopy our scales and axis for posterity:
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

# 4. Marks -- lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = data,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

# 5. Note: I put interactions in my marks call here.  BUT now we want to actually DO something with our selection
## THIS IS ALL WE HAVE ADDED!
heat_map.observe(on_selected, 'selected')


# stir and combine into 1 figure
fig = bqplot.Figure(marks = [heat_map], 
                    axes = [c_ax, y_ax, x_ax])

fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(orientatio…

In [34]:
def on_selected(change):
    if len(change['owner'].selected) == 1: #only 1 selected
        i, j = change['owner'].selected[0] # grab the x/y coordinates
        v = data[i,j] # grab data value
        mySelectedLabel.value = 'Data Value = ' + str(v) # set our label

In [35]:
# 1. Data -- same

# 2. Scales -- recopy our scales and axis for posterity:
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

# 4. Marks -- lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = data,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

# 5. Note: I put interactions in my marks call here.  BUT now we want to actually DO something with our selection
## THIS IS ALL WE HAVE ADDED!
heat_map.observe(on_selected, 'selected')


# stir and combine into 1 figure
fig = bqplot.Figure(marks = [heat_map], 
                    axes = [c_ax, y_ax, x_ax])


# ADDED: putting widget and plot together
myDashboard = ipywidgets.VBox([mySelectedLabel, fig]) # have label on top of fig
myDashboard # show

In [36]:
data = np.random.random((10, 10, 20))
data

array([[[3.44716949e-02, 3.20490131e-01, 4.15446148e-01, ...,
         6.79580953e-01, 8.11608716e-01, 6.63831632e-01],
        [5.12119318e-01, 2.63591038e-02, 4.15936848e-01, ...,
         4.84525247e-02, 8.99820577e-01, 3.75524555e-02],
        [7.74999699e-01, 1.79635069e-01, 4.81866483e-04, ...,
         2.49421085e-01, 2.93919082e-01, 7.90380655e-02],
        ...,
        [9.34899061e-01, 4.44883530e-01, 2.76839558e-01, ...,
         5.33236358e-01, 3.63354408e-01, 8.92006052e-01],
        [3.44152494e-01, 8.14602461e-01, 1.90747809e-01, ...,
         7.01071719e-01, 2.04253999e-01, 6.55716201e-01],
        [6.89334828e-01, 5.32443897e-01, 7.00442088e-01, ...,
         8.05427484e-02, 3.54960870e-01, 4.44834405e-01]],

       [[4.99067175e-01, 7.53504689e-01, 3.67326482e-01, ...,
         1.16606111e-01, 4.75633082e-01, 6.33438776e-01],
        [6.35400331e-01, 4.66761534e-01, 9.03180057e-01, ...,
         5.81810350e-01, 9.00575623e-01, 4.42553415e-01],
        [1.96841517e-01, 

In [37]:
data.shape

(10, 10, 20)

In [38]:
data[0,0,:]
# we can see that no instead of 1 value, each "i,j" component
#  has an array of values

array([0.03447169, 0.32049013, 0.41544615, 0.17797887, 0.19870876,
       0.41359203, 0.70063718, 0.85152724, 0.37919944, 0.23518867,
       0.63585256, 0.619276  , 0.20417325, 0.22164351, 0.08548755,
       0.65242626, 0.06703877, 0.67958095, 0.81160872, 0.66383163])

In [39]:
# Scales: now add scales - colors, x & y
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Axis: create axis - for colors, x & y
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

In [40]:
# Marks: lets now re-do our heat map & add in some interactivity:
heat_map = bqplot.GridHeatMap(color = np.sum(data, axis=2),
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

In [41]:
# create label again
mySelectedLabel = ipywidgets.Label()

In [42]:
def on_selected(change):
    if len(change['owner'].selected) == 1: #only 1 selected
        i, j = change['owner'].selected[0] # grab the x/y coordinates
        v = data[i,j].sum() # grab data value at x/y index and sum along z
        mySelectedLabel.value = 'Data Sum = ' + str(v) # set our label

In [43]:
heat_map.observe(on_selected, 'selected')

In [44]:
fig = bqplot.Figure(marks = [heat_map], axes = [c_ax, y_ax, x_ax])

myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

In [45]:
i, j = 0, 0

In [46]:
data[i, j].sum()

8.36815937492948

In [47]:
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

In [48]:
x_axh = bqplot.Axis(scale = x_sch, label = 'Value of 3rd axis')
y_axh = bqplot.Axis(scale = y_sch, 
                    orientation = 'vertical', 
                    label='Frequency')

In [49]:
hist = bqplot.Hist(sample = data[i,j,:],
                   normalized = False, # normalized=False means we get counts in each bin
                   scales = {'sample': x_sch, 'count': y_sch}, # sample is data values, count is frequency
                   bins = 10) # number of bins

In [50]:
figh = bqplot.Figure(marks = [hist], axes = [x_axh, y_axh])
figh

Figure(axes=[Axis(label='Value of 3rd axis', scale=LinearScale()), Axis(label='Frequency', orientation='vertic…

In [51]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [63]:
hist.sample.shape

(20,)

In [53]:
def on_selected(change):
    if len(change['owner'].selected) == 1: #only 1 selected
        i, j = change['owner'].selected[0] # grab the x/y coordinates
        v = data[i,j].sum() # grab data value at x/y index and sum along z
        mySelectedLabel.value = 'Data Sum = ' + str(v) # set our label
        # NOW ALSO: update our histogram
        hist.sample = data[i,j,:]

In [54]:
# (1) Scales: x/y, colors
col_sc = bqplot.ColorScale(scheme = "Reds")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# (2) Axis: x/y, colors
c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')

# (3) Marks: heatmap
heat_map = bqplot.GridHeatMap(color = np.sum(data, axis=2),
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'}, # make interactive on click of each box
                              anchor_style = {'fill':'blue'}, # to make our selection blue
                              selected_style = {'opacity': 1.0}, # make 100% opaque if box is selected
                              unselected_style = {'opacity': 0.8}) # make a little see-through if not

# (4) Link selection on heatmap to other things
heat_map.observe(on_selected, 'selected')

# (5) Paint heatmap canvas, don't display yet:
fig_heatmap = bqplot.Figure(marks = [heat_map], axes = [c_ax, y_ax, x_ax])

In [55]:
# (1) scales: x/y, linear
x_sch = bqplot.LinearScale() # range of z-axis data
y_sch = bqplot.LinearScale() # frequency of z-axis data in bins

# (2) axis: x/y
x_axh = bqplot.Axis(scale = x_sch, label = 'Value of 3rd axis')
y_axh = bqplot.Axis(scale = y_sch, 
                    orientation = 'vertical', 
                    label='Frequency')

# (3) Marks: histogram - start with just 0,0 in i/j -- can do other place holders
hist = bqplot.Hist(sample = data[0,0,:],
                   normalized = False, # normalized=False means we get counts in each bin
                   scales = {'sample': x_sch, 'count': y_sch}, # sample is data values, count is frequency
                   bins = 5) # number of bins

# (4) NO LINKING ON HISTOGRAM SIDE

# (5) Paint histogram canvas, don't display yet
fig_hist = bqplot.Figure(marks = [hist], axes = [x_axh, y_axh])

In [56]:
# side by side figures
figures = ipywidgets.HBox([fig_heatmap, fig_hist])

# label on top
myDashboard = ipywidgets.VBox([mySelectedLabel, figures])
myDashboard

In [57]:
# mess with figure layout:
fig_heatmap.layout.min_width = '500px' # feel free to change for your screen
fig_hist.layout.min_width = '500px'

# side by side figures
figures = ipywidgets.HBox([fig_heatmap, fig_hist])

# label on top
myDashboard = ipywidgets.VBox([mySelectedLabel, figures])
myDashboard

In [58]:
bins_slider = ipywidgets.IntSlider(value=5, min=1, max=data.shape[2]) # don't make more bins than data points!

In [59]:
ipywidgets.jslink((bins_slider, 'value'), (hist, 'bins'))

Link(source=(IntSlider(value=5, max=20, min=1), 'value'), target=(Hist(bins=5, colors=['steelblue'], interacti…

In [60]:
# mess with figure layout:
fig_heatmap.layout.min_width = '500px' # feel free to change for your screen
fig_hist.layout.min_width = '500px'

# side by side figures
figures = ipywidgets.HBox([fig_heatmap, fig_hist])

# label on top to the left, bins slider to the right
controls = ipywidgets.HBox([mySelectedLabel, bins_slider])

# combined
myDashboard = ipywidgets.VBox([controls, figures])
myDashboard

In [61]:
arr = np.random.random((8, 8))

color_sc = bqplot.ColorScale(colors = ["black", "white"])

heatmap = bqplot.GridHeatMap(color = arr, scales = {'color': color_sc},
                            row = ["one", "two", "three", "four", "five", "six", "seven", "eight"],
                            column = ["a", "b", "c", "d", "e", "f", "g", "h"])
fig = bqplot.Figure(marks = [heatmap])
display(fig)

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.03630…